### ISSUE TITLE
Upload CLI doesn't work in production

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/upload-service#124]
Hardcoded environment within the config.json doesn't work for production upload api url

**Comment by brainstorm** [comment]
I concur, following the official README.md indications I end up here:

```bash
$ source config/environment
DEPLOYMENT STAGE IS "dev"
source config/environment.dev
$ scripts/upload-api
DEBUG:connexion.app:Root Path: /Users/romanvg/dev/upload-service/upload/lambdas/api_server
DEBUG:connexion.app:Specification directory: /Users/romanvg/dev/upload-service/upload/lambdas/api_server
DEBUG:connexion.app:Setting error handlers
DEBUG:connexion.apis.abstract:Loading specification: /Users/romanvg/dev/upload-service/upload/lambdas/api_server/../../../config/upload-api.yml
DEBUG:connexion.apis.abstract:Read specification
Traceback (most recent call last):
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/common.py", line 24, in wrapper
    return method(*args, **kwargs)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/validator20.py", line 141, in validate_json
    cls=Draft4Validator,
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/ref_validators.py", line 53, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: '${API_HOST}' does not match '^[^{}/ :\\\\]+(?::\\d+)?$'

Failed validating 'pattern' in schema['properties']['host']:
    {'description': 'The host (name or ip) of the API. Example: '
                    "'swagger.io'",
     'pattern': '^[^{}/ :\\\\]+(?::\\d+)?$',
     'type': 'string'}

On instance['host']:
    '${API_HOST}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/upload-api", line 34, in <module>
    config = factory.create_config_obj(chalice_stage_name=os.environ['DEPLOYMENT_STAGE'])
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/chalice/cli/factory.py", line 114, in create_config_obj
    app_obj = self.load_chalice_app()
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/chalice/cli/factory.py", line 172, in load_chalice_app
    app = importlib.import_module('app')
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "scripts/../chalice/app.py", line 52, in <module>
    app = get_chalice_app(create_app().app)
  File "/Users/romanvg/dev/upload-service/upload/lambdas/api_server/__init__.py", line 27, in create_app
    app.add_api(swagger_spec_path, resolver=resolver, validate_responses=True)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/connexion/apps/abstract.py", line 159, in add_api
    options=api_options.as_dict())
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/connexion/apis/abstract.py", line 100, in __init__
    validate_spec(spec)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/validator20.py", line 90, in validate_spec
    http_handlers=http_handlers,
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/common.py", line 29, in wrapper
    sys.exc_info()[2])
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/common.py", line 24, in wrapper
    return method(*args, **kwargs)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/validator20.py", line 141, in validate_json
    cls=Draft4Validator,
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/swagger_spec_validator/ref_validators.py", line 53, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/Users/romanvg/.miniconda/envs/hca/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: ('\'${API_HOST}\' does not match \'^[^{}/ :\\\\\\\\]+(?::\\\\d+)?$\'\n\nFailed validating \'pattern\' in schema[\'properties\'][\'host\']:\n    {\'description\': \'The host (name or ip) of the API. Example: \'\n                    "\'swagger.io\'",\n     \'pattern\': \'^[^{}/ :\\\\\\\\]+(?::\\\\d+)?$\',\n     \'type\': \'string\'}\n\nOn instance[\'host\']:\n    \'${API_HOST}\'', <ValidationError: "'${API_HOST}' does not match '^[^{}/ :\\\\\\\\]+(?::\\\\d+)?$'">)
```

I guess that one or more of the hardcoded variables, like `DCP_DNS_DOMAIN='data.humancellatlas.org'` should be parametrized in order to deploy/test on other organizations?
