### ISSUE TITLE
If you query validation_status before validation has been performed you get a 500 error

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#358]
Using the new hca upload library, I did:
```
import time
from hca.upload import UploadService

upload = UploadService(deployment_stage="dev", api_token="XXXXXXXX")
area_uuid = str(uuid.uuid4())
area = upload.create_area(area_uuid=str(uuid.uuid4()))
area.upload_files(file_paths=["data.fastq.gz"], report_progress=True)
area.validate_files(file_list=["data.fastq.gz"], validator_image="humancellatlas/upload-validator-example:14")
time.sleep(5)
z = area.validation_status(filename="data.fastq.gz")
print(z)
```

Result is an exception at first:

```
UploadArea s3://org-humancellatlas-upload-dev/28ae4169-17c7-4e83-b1f6-43506e3ae1f5/
[{'name': u'data.fastq.gz'}, {'name': u'metadata.json'}]
Traceback (most recent call last):
  File "./x.py", line 38, in <module>
    z = area.validation_status(filename="data.fastq.gz")
  File "/Users/sampierson/Development/HCA/dcp-cli/hca/upload/upload_area.py", line 189, in validation_status
    return self.upload_service.api_client.validation_status(area_uuid=self.uuid, filename=filename)
  File "/Users/sampierson/Development/HCA/dcp-cli/hca/upload/lib/api_client.py", line 201, in validation_status
    response = self._make_request('get', path=path)
  File "/Users/sampierson/Development/HCA/dcp-cli/hca/upload/lib/api_client.py", line 228, in _make_request
    content=response.content))
hca.upload.lib.api_client.UploadApiException: GET returned 500 Server Error: Internal Server Error for url: https://upload.dev.data.humancellatlas.org/v1/area/28ae4169-17c7-4e83-b1f6-43506e3ae1f5/data.fastq.gz/validate, content returned={
  "detail": "None is not of type 'string'\n\nFailed validating 'type' in schema['properties']['validation_results']:\n    {'description': 'validation state and errors', 'type': 'string'}\n\nOn instance['validation_results']:\n    None",
  "status": 500,
  "title": "Response body does not conform to specification",
  "type": "about:blank"
}
```

Then later, after validation has been performed:

```
{u'validation_status': u'VALIDATED', u'validation_results': u'valid\n'}
```

**Comment by parthshahva** [comment]
@parthshahva confirm this is fixed and then close
