### ISSUE TITLE
PUT files_info with verbose option is broken

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#373]
"hca upload list -l" is broken

```
hca upload list -l
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/hca/upload/lib/api_client.py", line 232, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://upload.dev.data.humancellatlas.org/v1/area/deadbeef-dead-dead-dead-beeeeeeeeeef/files_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hca", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/hca/cli.py", line 131, in main
    result = parsed_args.entry_point(parsed_args)
  File "/usr/local/lib/python3.6/site-packages/hca/upload/cli/list_area_command.py", line 23, in __init__
    for f in upload_area.list(detail=args.long):
  File "/usr/local/lib/python3.6/site-packages/hca/upload/upload_area.py", line 85, in list
    files_info = self.upload_service.api_client.files_info(self.uuid, file_list)
  File "/usr/local/lib/python3.6/site-packages/hca/upload/lib/api_client.py", line 138, in files_info
    response = self._make_request('put', path=path, json=file_list)
  File "/usr/local/lib/python3.6/site-packages/hca/upload/lib/api_client.py", line 238, in _make_request
    content=response.content))
hca.upload.lib.api_client.UploadApiException: PUT returned 500 Server Error: Internal Server Error for url: https://upload.dev.data.humancellatlas.org/v1/area/deadbeef-dead-dead-dead-beeeeeeeeeef/files_info, content returned=b'{\n  "detail": "None is not of type \'object\'\\n\\nFailed validating \'type\' in schema[\'items\'][\'properties\'][\'checksums\']:\\n    {\'properties\': {\'crc32c\': {\'description\': \'CRC32C\', \'type\': \'string\'},\\n                    \'s3_etag\': {\'description\': \'S3 ETag\', \'type\': \'string\'},\\n                    \'sha1\': {\'description\': \'SHA1\', \'type\': \'string\'},\\n                    \'sha256\': {\'description\': \'SHA256\', \'type\': \'string\'}},\\n     \'type\': \'object\'}\\n\\nOn instance[0][\'checksums\']:\\n    None",\n  "status": 500,\n  "title": "Response body does not conform to specification",\n  "type": "about:blank"\n}\n'
```

**Comment by parthshahva** [comment]
@sampierson could you confirm this has been fixed and can be closed? The code indicates it might be fixed

**Comment by sampierson** [comment]
Not fixed in dev:
```
$ hca upload list -l
Traceback (most recent call last):
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/lib/python3.6/site-packages/hca/upload/lib/api_client.py", line 232, in _make_request
    response.raise_for_status()
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://upload.dev.data.humancellatlas.org/v1/area/deadbeef-dead-dead-dead-beeeeeeeeeef/files_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/bin/hca", line 11, in <module>
    sys.exit(main())
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/lib/python3.6/site-packages/hca/cli.py", line 136, in main
    result = parsed_args.entry_point(parsed_args)
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/lib/python3.6/site-packages/hca/upload/cli/list_area_command.py", line 23, in __init__
    for f in upload_area.list(detail=args.long):
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/lib/python3.6/site-packages/hca/upload/upload_area.py", line 85, in list
    files_info = self.upload_service.api_client.files_info(self.uuid, file_list)
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/lib/python3.6/site-packages/hca/upload/lib/api_client.py", line 138, in files_info
    response = self._make_request('put', path=path, json=file_list)
  File "/Users/sampierson/Development/HCA/upload-service/venv/36/lib/python3.6/site-packages/hca/upload/lib/api_client.py", line 238, in _make_request
    content=response.content))
hca.upload.lib.api_client.UploadApiException: PUT returned 500 Server Error: Internal Server Error for url: https://upload.dev.data.humancellatlas.org/v1/area/deadbeef-dead-dead-dead-beeeeeeeeeef/files_info, content returned=b'{\n  "detail": "None is not of type \'object\'\\n\\nFailed validating \'type\' in schema[\'items\'][\'properties\'][\'checksums\']:\\n    {\'properties\': {\'crc32c\': {\'description\': \'CRC32C\', \'type\': \'string\'},\\n                    \'s3_etag\': {\'description\': \'S3 ETag\', \'type\': \'string\'},\\n                    \'sha1\': {\'description\': \'SHA1\', \'type\': \'string\'},\\n                    \'sha256\': {\'description\': \'SHA256\', \'type\': \'string\'}},\\n     \'type\': \'object\'}\\n\\nOn instance[0][\'checksums\']:\\n    None",\n  "status": 500,\n  "title": "Response body does not conform to specification",\n  "type": "about:blank"\n}\n'
```
